[[constraint]]
  name = "ekyu.moe/base91"
  version = "^0.2.2"

[[constraint]]
  name = "ekyu.moe/base256"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/kyokomi/emoji"
  version = "^1.5"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "^0.0.9"

[[constraint]]
  name = "github.com/atotto/clipboard"
  branch = "master"

[[constraint]]
  name = "github.com/awnumar/memguard"
  version = "^0.13.2"

[[constraint]]
  name = "github.com/fatih/color"
  version = "^1.5.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "^1.4.1"
