[[constraint]]
  name = "ekyu.moe/base91"
  version = ">=0.2.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.3.0"
